"""updating db

Revision ID: 22c4bba14b1b
Revises: aab6cc11fa5d
Create Date: 2021-06-10 15:28:48.307044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c4bba14b1b'
down_revision = 'aab6cc11fa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('approved', sa.String(length=1), nullable=True))
    op.add_column('user', sa.Column('registration_id', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('registration_key', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('reset_password_key', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('block_user', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'block_user')
    op.drop_column('user', 'reset_password_key')
    op.drop_column('user', 'registration_key')
    op.drop_column('user', 'registration_id')
    op.drop_column('user', 'approved')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
